# Generated by Django 6.0.3 on 2026-03-11 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[
                    ('banh-keo', 'Bánh kẹo'),
                    ('nuoc-uong', 'Nước uống'),
                    ('thuc-pham', 'Thực phẩm'),
                    ('do-kho', 'Đồ khô'),
                    ('do-hop', 'Đồ hộp'),
                    ('quan-ao', 'Quần áo'),
                    ('giay-dep', 'Giày dép'),
                    ('phu-kien', 'Phụ kiện'),
                    ('do-gia-dung', 'Đồ gia dụng'),
                    ('my-pham', 'Mỹ phẩm'),
                    ('do-dien-tu', 'Đồ điện tử'),
                ],
                default='thuc-pham',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
